import { SITE_URL } from "@constants/index";
import { STAGE_META, computeStage, decodeShareCode } from "@lib/rubric";

const BASE = SITE_URL.replace(/\/$/, "");

/** Agent-facing static docs, generated by scripts/generate-agent-files.ts. */
export const AGENT_FILES = [
  { path: "/llms.txt", title: "llms.txt" },
  { path: "/llms-full.txt", title: "llms-full.txt" },
  { path: "/skill.md", title: "Agent Skill" },
] as const;

/** Anchor of the visible copy-prompt block. */
export const ASK_AGENT_ID = "ask-an-agent";

/** Prompt for a visitor's own AI assistant to run the assessment conversationally. */
export function assessPrompt(): string {
  return [
    `Read ${BASE}/skill.md and use it to run the Validator Beat assessment with me (full reference: ${BASE}/llms-full.txt).`,
    "",
    "Ask me the six questions one at a time. If my setup falls between two answers, help me pick the worse one; if I can't tell, use \"not sure\". Then tell me my Stage, which slices hold me back and the cheapest fix for each, and give me my Validator Beat share link.",
    "",
    "My setup, to start: [validators, execution and consensus clients, hosting providers and regions, signer / key setup].",
  ].join("\n");
}

/** Prompt for a visitor's own AI assistant to explain a specific result. */
export function resultPrompt(code: string): string {
  const answers = decodeShareCode(code);
  const stage = answers ? computeStage(answers) : null;
  const stageText = stage == null ? "" : `, which is ${STAGE_META[stage].name}`;
  const goal =
    stage === 2
      ? "and what I need to keep doing to stay at Stage 2"
      : `and the cheapest changes to reach ${STAGE_META[stage === 0 ? 1 : 2].name}`;
  return [
    `Read ${BASE}/llms-full.txt. My Validator Beat result is ${code} (${BASE}/${code}/)${stageText}.`,
    "",
    `Explain what each slice means for my setup, which single failures I'm still exposed to, ${goal}.`,
    "",
    "My setup: [validators, execution and consensus clients, hosting providers and regions, signer / key setup].",
  ].join("\n");
}
